services:
  - type: web
    name: gym-api
    env: node
    rootDir: src/gym-api
    buildCommand: npm install
    startCommand: npm start
    buildFilter:
      paths:
        - src/gym-api/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard or via secret
      - key: JWT_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

  - type: web
    name: gympoint
    env: node
    rootDir: src/gympoint
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    buildFilter:
      paths:
        - src/gympoint/**
    envVars:
      - key: NODE_ENV
        value: production
      # Add more env vars as needed, e.g. API_URL, etc.